services:
  backuponepass:
    build:
      context: .
    container_name: backuponepass
    hostname: backuponepass
    environment:
      - USER=${BACKUP_ONE_PASS_USER:?error}
      - PASSWORD=${BACKUP_ONE_PASS_PASSWORD:?error}
      - GID=${BACKUP_ONE_PASS_GID:?error}
      - UID=${BACKUP_ONE_PASS_UID:?error}
      - TZ=${BACKUP_ONE_PASS_TZ:?error}
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE:?error}
      - ONEPASSWORD_EMAIL=${BACKUP_ONE_PASS_ONEPASSWORD_EMAIL:?error}
      - ONEPASSWORD_SECRET_KEY=${BACKUP_ONE_PASS_ONEPASSWORD_SECRET_KEY:?error}
      - ONEPASSWORD_PASSWORD=${BACKUP_ONE_PASS_ONEPASSWORD_PASSWORD:?error}
      - ONEPASSWORD_TOTP_SECRET=${BACKUP_ONE_PASS_ONEPASSWORD_TOTP_SECRET:?error}
      - VNC_PASSWORD=${BACKUP_ONE_PASS_VNC_PASSWORD:?error}
      - DEBUG_MODE=${DEBUG_MODE}
    # DEBUG Purposes:
    ports:
      - "6080:6080" # noVNC HTML5 interface (access via browser)—noVNC Connection endpoint http://<IPv4>:6080/vnc.html
      - "5900:5900" # raw VNC (optional)
    volumes:
      - /dev/shm:/dev/shm # Shared memory
      - /run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
      - ./docker/data:/backuponepass/data # 1Password Data Output
    cap_add:
      - SYS_PTRACE
    restart: on-failure
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
