name: 🐛 Bug
description: Make a report to help us improve
title: '[BUG] <title>'
labels: [bug]
assignees: [NorkzYT]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Does this issue exist in the latest version?
      description: Please view all releases to confirm that this issue hasn't already been fixed.
      options:
        - label: I am using the latest release
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior?
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - all
        - ubuntu-latest or ubuntu-20.04
        - ubuntu-18.04
        - debian-latest or debian-12.2
        - debian-12
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior?
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output which is obtained after enabling debug logging. This will be automatically formatted into code, so no need for backticks.
      placeholder: |
        1. Re-running the workflow with debug logging enabled.
        2. Copy or download the log archive.
        3. Paste the contents here or upload the file in a subsequent comment.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? or References?

        Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
