name: Bump 1Password Version

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 4 * * *" # every day at 04:00 UTC
  workflow_dispatch: {}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest stable 1Password version
        id: get_version
        run: |
          LATEST=$(curl -s https://releases.1password.com/linux/ \
            | grep -oP 'Updated to \K[\d\.\-]+(?= on)' \
            | head -n2 \
            | tail -n1)
          if [[ -z "$LATEST" ]]; then
            echo "❌ failed to find stable version" >&2
            exit 1
          fi
          echo "version=$LATEST" >> $GITHUB_OUTPUT

      - name: Read current version.json
        id: get_current
        run: |
          CURRENT=$(jq -r .version docker/config/version.json)
          echo "current=$CURRENT" >> $GITHUB_OUTPUT

      - name: Update version.json
        if: ${{ steps.get_current.outputs.current != steps.get_version.outputs.version }}
        run: |
          jq --arg v "${{ steps.get_version.outputs.version }}" \
             '.version = $v' docker/config/version.json \
            > docker/config/version.tmp.json \
           && mv docker/config/version.tmp.json docker/config/version.json

      - name: Commit & Open Pull Request
        if: ${{ steps.get_current.outputs.current != steps.get_version.outputs.version }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_FOR_PR }}
          commit-message: "chore: bump 1Password → ${{ steps.get_version.outputs.version }}"
          branch: "bump-1password-${{ steps.get_version.outputs.version }}"
          title: "Bump 1Password to ${{ steps.get_version.outputs.version }}"
          body: |
            This PR updates 1Password to **${{ steps.get_version.outputs.version }}**.
            CI will verify the Docker build before merge.
