name: Bump 1Password Version

# run once daily (or adjust cron), and allow manual trigger
on:
  schedule:
    - cron: "0 4 * * *" # every day at 04:00 UTC
  workflow_dispatch: {}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest stable 1Password version
        id: get_version
        run: |
          LATEST=$(curl -s https://releases.1password.com/linux/ \
            | grep -oP 'Updated to \K[\d\.\-]+(?= on)' \
            | head -n2 \
            | tail -n1)
          if [[ -z "$LATEST" ]]; then
            echo "❌ failed to find stable version" >&2
            exit 1
          fi
          echo "version=$LATEST" >> $GITHUB_OUTPUT

      - name: Bail if already up-to-date
        run: |
          CURRENT=$(jq -r '.version' version.json)
          if [[ "$CURRENT" == "${{ steps.get_version.outputs.version }}" ]]; then
            echo "✅ version.json already at $CURRENT — nothing to do."
            exit 0
          fi

      - name: Update version.json
        run: |
          jq --arg v "${{ steps.get_version.outputs.version }}" \
             '.version = $v' version.json \
            > version.tmp.json \
           && mv version.tmp.json version.json

      - name: Commit & Open Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: bump 1Password → ${{ steps.get_version.outputs.version }}"
          branch: "bump-1password-${{ steps.get_version.outputs.version }}"
          title: "Bump 1Password to ${{ steps.get_version.outputs.version }}"
          body: |
            This PR updates 1Password to **${{ steps.get_version.outputs.version }}**.
            CI will verify the Docker build before merge.
